### ISSUE TITLE
standard_init_linux.go:211 when I try to cross compile from amd64

### ISSUE THREAD

**Issue by radiodee1** [emacski/tensorflow-serving-arm#1]
I get this error and I don't know why.

    standard_init_linux.go:211: exec user process caused "exec format error"

I tried to build arm32v7 and also arm64v8. I'm running ubuntu disco dingo. I get to the point where 5041 processes have completed and the message on the screen just before this error is below:

> Removing intermediate container ef2fe797a8b0
>  ---> bf1f28450744
> Step 15/22 : FROM ${ARCH}/ubuntu:bionic as tensorflow_model_server
> bionic: Pulling from arm32v7/ubuntu
> 5379ca036368: Pull complete 
> 4ede4c7641a5: Pull complete 
> 0994f5ac8c79: Pull complete 
> a81b96316730: Pull complete 
> Digest: sha256:46fe74f7b605368593fd21ff9db45429d9faa86550ad13f7eefb2c995c69b271
> Status: Downloaded newer image for arm32v7/ubuntu:bionic
>  ---> 6348795f7982
> Step 16/22 : COPY --from=build /tensorflow-serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server /usr/bin/tensorflow_model_server
>  ---> ec679480db38
> Step 17/22 : EXPOSE 8500
>  ---> Running in 4020fd341139
> Removing intermediate container 4020fd341139
>  ---> 3466dc1ccfac
> Step 18/22 : EXPOSE 8501
>  ---> Running in 1fd2b5d81e91
> Removing intermediate container 1fd2b5d81e91
>  ---> f50abb691752
> Step 19/22 : ENV MODEL_BASE_PATH=/models
>  ---> Running in 8834cdb7172a
> Removing intermediate container 8834cdb7172a
>  ---> 94c5e7e0aa60
> Step 20/22 : RUN mkdir -p ${MODEL_BASE_PATH}
>  ---> Running in 99408f90eaf7

I am interested in a binary for tensorflow_model_server for the armhf processor. I really don't know much about containers.

**Comment by emacski** [comment]
Yeah, since the upstream project relies on hermetic builds and uses docker to isolate the build env, I have done the same. Unfortunately, that means docker itself requires a bit of coercing to cross-build arm images on an x86 linux host. I believe this is what you are running up against as docker tries to execute an armeabi `mkdir` on your x86 host.

There are a couple of ways for obtaining the precompiled binaries that are used in this project.

Binaries for each release by architecture are available to download here: https://github.com/emacski/tensorflow-serving-arm/releases

Just note that these binaries are created for the resulting docker images (i.e. they are dynamically linked c++ executables compiled against Ubuntu 18.04 libs) 

You can also copy the binary from one of the existing docker images / containers:
```bash
docker create --name tfsbin emacski/tensorflow-serving:1.14.0-arm32v7
docker cp tfsbin:/usr/bin/tensorflow_model_server .
docker rm tfsbin
```

If you are still interested in compiling a binary (again, with the same caveat as the note above), you could do something like this:

Compile arm32v7 (vfpv4) binary
```bash
mkdir /tmp/bazel_root
docker run --rm -v /tmp/bazel_root:/tmp/bazel_root emacski/tensorflow-serving:1.14.0-devel \
  bazel --output_user_root=/tmp/bazel_root \
  build --config=arm32v7 tensorflow_serving/model_servers:tensorflow_model_server
# binary should end up at bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
# where bazel-bin is a symlink to the tmp dir created first.
```

The "devel" image encapsulates the entire build env for a given release including source.

Hope that gets you something you can use.

**Comment by radiodee1** [comment]
thanks. I tried the latest download from the download page. I am using stretch on my pi. It says it cannot run as it needs glibc_2.27 . Are your images compiled against stretch or maybe the newer buster? Are any of them compiled against stretch? if so which ones? BTW, thanks for your time.

**Comment by emacski** [comment]
`v1.11.1` and `v1.12.0` binaries were compiled against Ubuntu 16.04 (based on Debian stretch). All other binaries are compiled against Ubuntu 18.04 (based on Debian buster).

**Comment by radiodee1** [comment]
hi. Your tf-model-server for arm is great. I tried 1.12.0 and it ran but could not read my saved tensor2tensor model. I tried to cross compile and feel that that has a good chance of working if I can get ubuntu artful for the arm environment. I tried simply changing the 'ubuntu:bionic' listing in the Dockerfile.arm file to read 'ubuntu:artful' . Somehow though I think the bionic version is still loading. Sadly I don't know enough about docker to get the artful environment to load. Do you  have any suggestions? The reason it has to be artful is that I have a pi with stretch on it. I actually tried buster but I could not install tensorflow with pip as opencv was not compiled for buster yet. That is the reason I'm sticking with stretch. If I could install tensorflow in buster I would probably switch over to buster, and then I'm guesssing your arm tensorflow_model_server would work. On a whim I changed the Dockerfile.arm line that says 'ubuntu:bionic' to read 'debian:stretch'. It didn't do anything. I must be editing the wrong file. Can you point out the file where a change would result in artful or stretch loading as the arm environment?

**Comment by emacski** [comment]
Initial question: I know you mentioned that you are interested in an armhf binary executable, but do you have installed, or are you able to install docker on your pi?

and then...

Are you getting an error similar to this?
```
I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /home/alarm/model/1
[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/text_format.cc:307] Error parsing text-format tensorflow.SavedModel: 162018:18: Message type "tensorflow.FunctionDef" has no field named "arg_attr".
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:259] SavedModel load for tags { serve }; Status: fail. Took 2425432 microseconds.
E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: model version: 1} failed: Data loss: Can't parse ~/model/1/saved_model.pbtxt as text proto
```
If so, this might actually be a bug in the upstream project or one of its dependencies: https://github.com/tensorflow/serving/issues/1386 

I performed a quick test using armhf binaries on armv7 platform exporting the example model from tensor2tensor to a saved model (using `t2t-exporter`). For versions `v1.11.1`, `v1.12.0` and `v1.13.0` of tf-serving I received the error above when attempting to load the model. The latest version, `v1.14.0`, seems to load the model fine:
```
I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: model version: 1}
```

Regarding the docker base build / devel image: 

The way I have this project set up, I don't actually control what base image is used for the build. The values you are changing in the docker file only affect the resulting application images for this project that contain the binary and runtime only.

If you see the line:
```Dockerfile
# tools/docker/Dockerfile.arm
FROM tensorflow/serving:$TFS_VERSION-devel as devel
```
I am actually using the upstream project's build / devel image as the base of my own build / devel image (this makes things much easier for me to maintain, at the expense of introducing some complexity). Here is the Dockerfile in the upstream project containing the base image and version: https://github.com/tensorflow/serving/blob/1.14.0/tensorflow_serving/tools/docker/Dockerfile.devel

**Comment by radiodee1** [comment]
Yes. The error is similar to the one in the beginning of the post.

**Comment by emacski** [comment]
I guess the good news is, `v1.11.1` and `v1.12.0` seem to run fine directly on your 32-bit arm platform. The bad news is, you've possibility hit an upstream bug when serving saved models from tensor2tensor. As far as I can tell this issue affects all architectures and versions `<=1.13.0` including the official amd64 builds. Note, however, those same versions will load and run saved models produced by other utilities.

Well, at this point I would urge you to install docker on your pi and use the corresponding docker image for tf-serving 1.14.0 (https://hub.docker.com/r/emacski/tensorflow-serving). You can use your existing OS and in this case it doesn't really matter what the OS is on your pi, all the dependencies are included and encapsulated in the image (glibc 2.28, etc..). Additionally, you can use the image / container in much of the same way you would use the standalone executable. One of the great benefits of this approach is that you shouldn't have any issues running the latest versions as they are released. This is also the intended use-case for this project.

**Comment by radiodee1** [comment]
I am having trouble writing a script to launch the docker arm container. I suspect this is not the right place to bring this up. Is there a better forum or should I open another issue? I am having trouble passing my saved model to the container. My current script looks like this:


        docker pull emacski/tensorflow-serving:1.14.0-arm32v7

        TESTDATA="$(pwd)/saved/t2t_train/" #chat_10/export/1564940385/"

        docker cp  $TESTDATA/chat_10/export/1564940385/ emacski/tensorflow-serving:1.14.0-arm32v7:/chat_10/.

        docker run -t --rm -p 8500:8500 \
            -v "$TESTDATA/chat_10/export/1564940385/" \
            -e MODEL_NAME=chat_10 -e MODEL_BASE_PATH="" \
            emacski/tensorflow-serving:1.14.0-arm32v7  # &
            
Where is a good place to ask about this?

**Comment by emacski** [comment]
No worries. Here are some pointers to get you started. I'm the one who urged you to go this route after all :). 

Ok so the quick and dirty:
```bash
docker pull emacski/tensorflow-serving:1.14.0-arm32v7

docker run --rm -ti -p 8500:8500 \
-v $(pwd)/saved/t2t_train/chat_10/export/1564940385:/models/chat_10/1 \
-e MODEL_NAME=chat_10  \
emacski/tensorflow-serving:1.14.0-arm32v7
```

A note about `docker run`: This command typically creates a new container from the image on every invocation (hence the `--rm` flag in the command above) and can be useful when running a containerized service managed by an external service manager like `initd` or `systemd` (also really useful for running in the foreground for development and debugging). Otherwise, you can have the docker daemon manage your containerized services in the background through the docker `create`, `start`, `stop`, `rm`, etc. commands. 

```bash
# I would really consider using an absolute path to the model here
docker create --name tensorflow_model_server -p 8500:8500 \
-v $(pwd)/saved/t2t_train/chat_10/export/1564940385:/models/chat_10/1 \
-e MODEL_NAME=chat_10  \
emacski/tensorflow-serving:1.14.0-arm32v7

docker start tensorflow_model_server

# tail container stdout
docker logs -f tensorflow_model_server
```

Alternatively, you can "bake" your model into your own image:
```Dockerfile
# your_project/Dockerfile
FROM emacski/tensorflow-serving:1.14.0-arm32v7
ENV MODEL_NAME=chat_10
COPY saved/t2t_train/chat_10/export/1564940385 /models/${MODEL_NAME}/1
```

```bash
docker build -t my_model_server .
docker run --rm -ti -p 8500:8500 my_model_server
```

You can also create an alias if you wanted to simulate using the executable directly
```bash
alias tensorflow_model_server="docker run --rm --init -p 8500:8500 -p 8501:8501 -v $(pwd):$(pwd) --entrypoint tensorflow_model_server emacski/tensorflow-serving:1.14.0-arm32v7"

# then you can just
tensorflow_model_server --help
# or
tensorflow_model_server --model_name=chat_10 --model_base_path=$(pwd)/saved/t2t_train/chat_10/export/
```

**Comment by radiodee1** [comment]
this is what I'm trying right now. also in this post is an error message. Tomorrow I've got to make sure the model is actually on the pi where I think it should be. Thanks for the support.

        docker pull emacski/tensorflow-serving:1.14.0-arm32v7

        TESTDATA="$(pwd)/saved/t2t_train"
        MODEL_NAME="chat_10"
        EXPORT_NUM="1564940385"


        docker run -t --rm -p 8500:8500 \
            --mount type=bind,src=${TESTDATA}/${MODEL_NAME}/export/${EXPORT_NUM}/,dst=/${MODEL_NAME} \
            -e MODEL_NAME=$MODEL_NAME -e MODEL_BASE_PATH="" \
            --entrypoint tensorflow_model_server emacski/tensorflow-serving:1.14.0-arm32v7 \
            --port=8500 --model_name=${MODEL_NAME} --model_base_path=/$MODEL_NAME 
            

2019-08-14 21:23:09.687328: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2019-08-14 21:23:09.687416: I tensorflow_serving/model_servers/server_core.cc:561]  (Re-)adding model: chat_10
2019-08-14 21:23:09.688386: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:267] No versions of servable chat_10 found under base path /chat_10

I think the alias idea has some merrit for the pi, but I think I'll work on the shell script for a while and see if I cannot get that to work.

**Comment by emacski** [comment]
is your pbtxt file in the `1564940385` dir (i.e. something like: `1564940385/saved_model.pbtxt`)?

if yes, try changing your `docker run ...` to:

```bash
docker run --rm -ti -p 8500:8500 \
    -v ${TESTDATA}/${MODEL_NAME}/export/${EXPORT_NUM}:/models/${MODEL_NAME}/1 \
    -e MODEL_NAME=${MODEL_NAME} \
    emacski/tensorflow-serving:1.14.0-arm32v7
```

**Comment by radiodee1** [comment]
HI.

    #!/usr/bin/env bash

    docker pull emacski/tensorflow-serving:1.14.0-arm32v7

    TESTDATA="$(pwd)/saved/t2t_train"
    MODEL_NAME="chat_10"
    EXPORT_NUM="1564940385"

    docker run --mount type=bind,src=${TESTDATA}/${MODEL_NAME}/,dst=/${MODEL_NAME}  --entrypoint ls emacski/tensorflow-serving:1.14.0-arm32v7  -hal chat_10

    docker run -t --rm -p 8500:8500 \
        --mount type=bind,src=${TESTDATA}/${MODEL_NAME}/,dst=/${MODEL_NAME} \
        -e MODEL_NAME=$MODEL_NAME -e MODEL_BASE_PATH="" \
        --entrypoint tensorflow_model_server emacski/tensorflow-serving:1.14.0-arm32v7 \
        --port=8500 --model_name=${MODEL_NAME} --model_base_path=/$MODEL_NAME/export/ \
        
finally this worked. I did have to go back to my MODEL_NAME folder and make sure everything was there. I don't know if that was my problem yesterday and last night. Thank you for your help and this great github repository.

**Comment by emacski** [comment]
Great! I'm glad you were able to get things up and running on your pi.
