### ISSUE TITLE
tensorflow serving arm  image can't exec into a running container

### ISSUE THREAD

**Issue by weluna** [emacski/tensorflow-serving-arm#3]
I use the image (emacski/tensorflow-serving   1.14.0-linux_arm64_armv8-a) from docker hub. 
Running is OK, but can't exec into the container.  I try bash、sh all failed，attach is also failed. 
Show such wrong message: "exec: \"bash\": executable file not found in $PATH": unknown.

**Comment by emacski** [comment]
There is no shell. The base docker images used for this project are [discolix](https://github.com/discolix/discolix) "distroless" images. My discolix project is based off of, and heavily influenced by, Google's [distroless](https://github.com/GoogleContainerTools/distroless) project with the major difference being that my discolix project provides ARM images.

That being said, these images are designed to only include a bare minimum linux system required to run a given application and no more (i.e. these base images are not "full" linux distros).

What specifically are you trying to accomplish? I might be able to assist you with a solution that does not require a shell.

**Comment by weluna** [comment]
Thank you for your reply!
Actually, I used the docker client for java exec some linux command(such as: ls、cat) to get model file and config file info in the running container, that may inappropriate. I’m trying to use another way to implements this feature. I also think if the image support exec will more friendly.

**Comment by weluna** [comment]
Thank you for your reply!
Actually, I used the docker client for java exec some linux command(such as: ls、cat) to get model file and config file info in the running container, that may inappropriate. I’m trying to use another way to implements this feature. I also think if the image support exec will more friendly.

**Comment by emacski** [comment]
Just FYI, as of version 2.0.0 this project now has "debug" images which include some common system utilities (busybox) for exploring these images / containers with exec commands or an interactive shell.

https://github.com/emacski/tensorflow-serving-arm#debug-images
