### ISSUE TITLE
Is a directory: '/tmp/pip-req-build-w20bge16/'

### ISSUE THREAD

**Issue by xiongmingzhi** [emacski/tensorflow-serving-arm#9]
pip isntall tensorflow_model_server-1.12.0-linux_armhf_vfpv3.tar.gz
[Errno 21] Is a directory: '/tmp/pip-req-build-w20bge16/'

**Comment by emacski** [comment]
I'm not sure I understand this issue.

It's not possible to install a model server binary or docker image as a python package.

**Comment by emacski** [comment]
Haven't heard back
